name: CI and Publish

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run CI
        run: npm run ci

  publish-npm:
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Set package registry
        run: npm config set registry https://npm.pkg.github.com
      - name: GitHub package registry authentication
        run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.PAT }}
      - name: Npm registry authentication
        run: npm set //registry.npmjs.org/:_authToken ${{ secrets.npm_token }}
      - name: Publish the package to Github and Npm package registries
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}
